key_name              = "my-ec2-key"
jump_ami              = "ami-0f9de6e2d2f067fca"
private_ami           = "ami-0f9de6e2d2f067fca"
jump_instance_type    = "t3.medium"
private_instance_type = "t3.micro"
jump_ssh_cidr         = "0.0.0.0/0"
ecr_name              = "myapplication"
region                = "us-east-1"
