---
- name: Install Docker and AWS CLI on all servers (jump and private)
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies for Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install AWS CLI
      apt:
        name: awscli
        state: present

- name: Install Jenkins and configure Docker access on jump server
  hosts: jump
  become: yes
  tasks:
    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Add Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        filename: jenkins

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Enable and start Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Docker and Jenkins services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - docker
        - jenkins

    - name: Read Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password

    - name: Show Jenkins admin password
      debug:
        msg: "Initial Jenkins password: {{ jenkins_password['content'] | b64decode }}"



    - name: Copy PEM key to Jenkins home
      copy:
        src: /home/ac190-mohit/Documents/my-ec2-key.pem
        dest: /var/lib/jenkins/my-ec2-key.pem
        owner: jenkins
        group: jenkins
        mode: '0400'

- name: Configure Docker access for ubuntu user on private server
  hosts: private
  become: yes
  tasks:
    - name: Add ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Restart Docker to apply group change
      systemd:
        name: docker
        state: restarted
